/**
 * One unique 80–120 word paragraph per theme (24 total) for the
 * "About this design" section on /portfolio/[slug] and /demos/[slug].
 *
 * Each paragraph is intentionally distinct content: it covers the
 * theme's conversion mechanic, target industries, design influences,
 * and where the design WOULDN'T fit. That last bit ("less useful for")
 * is the SEO key — it gives Google enough non-overlapping signal to
 * treat each page as standalone content, not a templated description.
 */
export const portfolioCopy: Record<string, string> = {
  // ──────────────────────────────────────────────────────────────────
  // Round 3 — featured home-service brands (8)
  // ──────────────────────────────────────────────────────────────────
  "ironside-plumbing":
    "Built for emergency-service trades where the phone has to ring now. Hazard-stripe accents, brutalist Archivo Black headlines, and a phone-first hero that pulses on page load. Every conversion path leads to call-now — no quote forms hiding the number. The font system reads as 'service truck, but legible': Archivo Black for headlines, JetBrains Mono for badges and dispatch metadata. Useful when your buyer's search query is more often 'plumber near me at 2am' than 'best plumber in town.' Pairs well with 24/7 dispatch, after-hours surcharges, and any trade where missing a single call costs you the job.",
  "greenwise-lawn":
    "An organic palette (moss, cream, terracotta) for recurring lawn-care work. Booking-card hero with date pickers and instant pricing. Soft Fraunces serifs signal craft over scale — the message is 'we'll know your yard,' not 'we have 200 trucks.' Best fit for organic-leaning, neighborhood-scale operators who win on relationship quality, not lowest price. The booking card emphasizes the recurring rhythm: weekly mow, monthly fertilization, seasonal cleanup. Less useful for one-shot landscape projects — the gallery hero (Westwood Tree style) handles those better. Pair with a customer portal so subscribers can pause or skip a service week without calling.",
  "bellhorn-movers":
    "Calculator-led hero shows your move price in real time as you tap fields. Navy + orange + hard-shadow buttons keep it playful for a category most movers treat as transactional. Trust-strip credentials reassure without the corporate vibe. The instant-quote pattern works because moving is a high-anxiety purchase: people abandon long quote forms but trust an upfront flat-rate price. Also strong for junk removal, hauling, and any trade that prices by hours or square footage. The Bricolage Grotesque + hard-shadow buttons deliver friendly competence — buyers trust them with their couch but the brand still doesn't feel boring corporate.",
  "heritage-painters":
    "Editorial Charleston warm-craft. Terracotta + gold + ink palette, gallery-led hero showcasing project work, Fraunces italic for premium positioning. Built for painters and restorers who charge a premium and want their site to look like the work, not the truck. Best for established trades whose buyers research extensively before contacting — historic homes, custom carpentry, restoration. The gallery hero converts visitors who landed via a Pinterest pin or design blog mention. Less useful for emergency repairs or commodity work where price wins. Pair with a project journal CMS so the site stays current with seasonal commissions and award badges.",
  "brightside-cleaning":
    "Sky-and-mint gradient hero with a pillowy booking card. Friendly modern, recurring-services positioning. Plus Jakarta Sans + Caveat script for human warmth. Conversion path: pick a date, see your price, book — three taps. Built for residential cleaning, dog walking, and any service where the buyer signs up online without ever calling. The Caveat handwritten accents soften the booking widget without making the brand look amateur. Best when you want to feel like a small local team that just happens to be online-first; less useful when you need to project industrial scale or 24/7 emergency response.",
  "summit-roofing":
    "Industrial dark with Oswald display caps. Form-card hero captures storm-damage leads instantly. Black + orange glow signals urgency without screaming. Designed for roofers who get most of their leads from a hailstorm and a phone notification. The form-card pattern works because roof inspections sell as a free 'come look at my problem' visit — friction-low ask, high-conversion. Pairs well with insurance-claim workflows, GAF Master Elite or similar credential displays, and seasonal storm-response landing pages. Less useful for premium custom roofing where Heritage's gallery would convert better. The Oswald + JetBrains Mono pairing reads as professional industrial, not strip-mall contractor.",
  "westwood-tree":
    "Forest greens + safety orange. ISA-certified-arborist credibility hero with photo gallery. For arborists, landscapers, and rugged outdoor trades who want to look serious without looking corporate. Insurance and certifications front-and-center — the gallery hero showcases project size (giant oak removals, technical climbs) more effectively than text could. Pairs well with high-ticket project work where the buyer is comparing multiple quotes and wants reassurance the contractor can handle the job safely. Less useful for routine yard-maintenance services — Greenwise covers those better. The Oswald + Fraunces pairing communicates technical competence and craft without going corporate.",
  "voltcraft-electric":
    "High-voltage industrial. Black + electric yellow, license number prominent in the header, phone-first hero. Built for licensed electricians and HVAC techs running 24/7 emergency lines who need 'call now' to be the loudest pixel on the page. Pairs with after-hours dispatch fees, master-electrician credentials, and any trade where the buyer is staring at a blinking breaker box. Less useful for project-based panel upgrades — those want a form-card hero. The Inter Heavy + JetBrains Mono pairing keeps the brand legible at the small sizes (truck wraps, business cards, invoice tops) where a more dramatic display font would fall apart.",

  // ──────────────────────────────────────────────────────────────────
  // Round 1 — promoted theme options (2)
  // ──────────────────────────────────────────────────────────────────
  "premium-trade":
    "An editorial trade brand for contractors who want to feel premium without losing credibility. Bone + copper + ink with pipe-blue accents. Fraunces serif headlines, stat tiles, and a form-card hero. The opposite of 'we'll be there in 30 min' — engineered restraint over urgency. Useful when your buyer is comparing your bid against three others and you want to be the one that signals 'we don't haggle.' Pairs with multi-thousand-dollar service tickets, commercial accounts, and trades adjacent to architecture (HVAC retrofit, panel upgrades, plumbing rebuilds). Less useful for break-fix work where Ironside's urgency converts better. Stat tiles let you front-load credentials before the quote ask.",
  "doorstep-editorial":
    "Pickup-and-delivery service design. Address-bar hero takes a zip code and shows availability inline. Cream + forest + butter palette, italic editorial display. Built for laundry pickup, dog walking, oil delivery, and any recurring delivery brand where 'do you serve my address' is the first question. The address-bar pattern is genuinely high-converting — it instantly removes the buyer's biggest unanswered question without requiring them to commit to a form. Pairs with route-density operations (you serve your zip cluster well, others not at all) and subscription billing. The Instrument Serif italic feels editorial-magazine, signaling the brand cares about details.",

  // ──────────────────────────────────────────────────────────────────
  // Round 1 — non-featured (6)
  // ──────────────────────────────────────────────────────────────────
  "daylight-lounge":
    "An indie laundromat reimagined as a hospitality lounge. Cream + terracotta + sage pastels, Fraunces serif display, photo-collage hero. The conversion path centers on 'come hang out' rather than 'do a transaction' — a useful pattern for any service business that wants to feel like a third place. Coffee shops, co-working, mechanics with comfortable waiting rooms, even pediatric dentists who lean into the experience side of the visit. Less useful for trades where the customer never sets foot in your physical space. The Caveat script accents and DM Sans body keep the warmth from getting too precious — it's still a laundromat, just a nicer one.",
  "documentary-b2b":
    "B2B credentialed style for healthcare and hospitality laundry. Navy + yellow + red, ISO/OSHA/HIPAA strip up top, form-card hero for inbound contract leads. Built for compliance-sensitive vendors where 'we're certified' is the headline, not the footnote. Pairs with multi-year service contracts, RFP responses, and procurement-driven sales cycles where buyers verify credentials before they take a meeting. Less useful for residential-service trades — the formality alienates homeowners. Inter Tight + JetBrains Mono keeps it serious without going stuffy. Strong choice for commercial cleaning, medical-grade waste removal, food-service supply, or any vertical where 'compliance' is a buying criterion.",
  "swiss-editorial":
    "An independent design practice's portfolio site. Cream + ink + oxblood, Instrument Serif italic, tabular project index that hover-reveals. The hero is mostly type — long-form, headline-only, no decoration. Built for studios who don't pitch with bullet points. Useful pattern for architects, interior designers, photographers — any creative-led practice whose buyers evaluate primarily through the work itself, not through positioning copy. The tabular project index doubles as a credibility list (clients, years, disciplines) without being a wall of logos. Less useful for service businesses that need to convert cold traffic — this design assumes warm, referral-driven buyers.",
  "cinematic-dark":
    "A film-noir studio brand. Deep black + warm white + copper + teal, custom cursor, full-bleed atmosphere. Built for production companies and luxury creative — the kind of agency that makes you fill out a contact form and waits a week to reply. The custom cursor is bait: it signals you're talking to people who care about the texture of the experience, not just the conversion rate. Pairs with $50K+ project minimums, retainer clients, and inbound-only sales. Less useful for any business where the buyer is in a hurry; the design rewards lingering. Fraunces italic + Inter creates the editorial-but-cinematic register.",
  "webgl-experimental":
    "Acid green + electric blue developer-tools positioning. Hyper-tech with a custom cursor and orb hero. Built for AI tools, devtools, frontier-tech products that want to look like they're shipping at the edge — useful pattern if your buyer is a CTO who already uses Linear. The aesthetic is 'we know the new terminal emoji is U+1F4A1.' Inter Tight + JetBrains Mono keeps the geek-prestige cohesive. Pairs with self-serve free-tier funnels, dev-doc-led marketing, and Twitter-driven launches. Less useful for any audience that wouldn't recognize the visual references — for SaaS aimed at non-engineers, Switchback's emerald-glow restraint converts better.",
  "brutalist":
    "Pop-art neo-brutalism for a creative agency that's proud of being loud. Yellow + black + pink + cobalt, 4px hard borders, hard-shadow buttons, ALL CAPS mega type. Subtlety not invited. Useful inspiration for any brand whose competitive moat is volume — DTC food, energy drinks, streetwear, agencies whose pitch is 'we'll get you noticed.' Bricolage Grotesque + Funnel Display in 16vw mega type forces the page to commit. Less useful for any audience that values restraint or considers subtlety a virtue. Pairs with scarcity drops, viral campaigns, and brands whose buyers self-select on aesthetic at first glance.",

  // ──────────────────────────────────────────────────────────────────
  // Round 2 — non-featured (8)
  // ──────────────────────────────────────────────────────────────────
  "print-block-books":
    "An indie bookstore + zine press. Riso/halftone aesthetic, paper + navy + pink + green, dashed pink stamps. Conversion path: discover-then-subscribe, not browse-then-buy. Bookstore, but make it pop. Useful template for any retail business that survives on regulars rather than walk-ins — coffee roasters, record stores, vintage shops, craft butchers. The halftone overlays and Space Mono typewriter accents do the heavy lifting on personality. Pairs with email-newsletter-driven loyalty (a 'Friday picks' mailing list converts in this aesthetic). Less useful for high-volume retail or category killers — the design rewards careful browsing, not fast conversion.",
  "wildflower-stone":
    "Slow-goods florist + apothecary. Cream + sage + dusty rose + gold, Cormorant Garamond + EB Garamond, hand-drawn leaf dividers, all-italic navigation. The opposite of urgency — a useful pattern for any high-margin craft business that survives on returning customers, not first-time clicks. Florists, perfumeries, ceramic studios, herbalists, fine stationery. The all-italic navigation is a strong commitment: it forces every section to feel like an editorial spread. Pairs with seasonal product drops, named collections, and a 'shop this week' rhythm. Less useful for any product line that needs urgency or scarcity to convert — this design rewards considered purchases.",
  "angelos":
    "A heritage Brooklyn pizza joint, est. 1956. Newspaper-Italian-Americana with Bodoni Moda, parchment + tomato + mustard, double-rule borders, hand-stamp accents. Every conversion path leads to 'come in tonight' — useful for any restaurant whose moat is decades, not Yelp stars. Diners, bagel shops, Greek delis, classic steakhouses, anywhere the buyer's instinct is 'they've been here forever, they're probably good.' Bodoni Moda + Playfair italic does the heritage signaling; Caveat handwritten accents add a touch of staff personality. Less useful for new restaurants without backstory — the design rewards age. Pairs with Italian-American documentary aesthetics.",
  "still-point":
    "A wabi-sabi yoga studio. Bone + terracotta + sage with Noto Serif JP character marks, Cormorant italic, morphing organic hero shape. Quiet pacing, calm conversion. Ideal pattern for wellness, meditation, and recovery brands where 'no, that's not us' is half the message. Naturopaths, acupuncturists, sound baths, breathwork practices — anywhere the buyer is fatigued by hustle culture. The Japanese typography hints at the lineage without leaning into Oriental-fetishism. Less useful for high-energy fitness studios — those convert better with bolder, higher-contrast designs. Pairs with introductory-week pricing and a member portal where regulars book without thinking.",
  "north-fork":
    "An independent brewery + taproom. Forest + cream + mustard + oxblood, Archivo Black masthead, Crimson Pro italic lede, heritage badge mark. Beer-hall loud type for taproom hours. Useful template for any local hospitality brand that needs to feel both heritage and current. Distilleries, wineries, cocktail bars, neighborhood pubs, even barber shops with strong local tenure. The Archivo Black masthead is the visual signature — it photographs well on tap-room signage, can-label printing, and Instagram carousels. Pairs with seasonal release calendars, event nights, and merchandise drops. Less useful for restaurants where food is the lead and the bar is secondary.",
  "cask-vine":
    "A 22-seat natural wine bar. Wine + gold + cream, Italiana display, Cormorant italic accent. Deep, low-lit, elegant — the dinner-reservation kind of conversion. The site is the host: scarce seating, careful copy, no 'BOOK NOW' button. Useful pattern for hospitality brands where reservations are expressed as 'we'd love to seat you' rather than 'click to book.' Tasting menus, omakase counters, members-only lounges, prix-fixe-only restaurants. Italiana + Cormorant italic delivers the Italian-Riviera-loungy register that matches the price point. Less useful for high-volume hospitality — this design rewards restraint, not throughput. Pairs with a wine-by-the-glass list.",
  "mara-lin":
    "Fashion-photo darkroom. Near-black + warm-white + tan, Tenor Sans + DM Mono labels, custom cursor, full-bleed editorial figure. For photographers, directors, and fashion talent who don't list prices — the brief comes through email, not a pricing page. Useful for any creative whose work is the product and pricing is bespoke per job. Stylists, art directors, pattern designers, brand consultants. The custom cursor reads as 'we care about details and you should too.' Pairs with agency representation, an editorial portfolio of named clients, and email-only inquiry forms. Less useful for any service that benefits from listed prices or self-serve booking.",
  "switchback":
    "A Linear-style observability SaaS. Near-black grid + emerald glow + JetBrains Mono labels. Centered hero with a code-card preview, multi-tile feature grid, gradient text. Useful template for any developer-tools brand whose buyer evaluates by aesthetic before reading docs. Frontend platforms, monitoring tools, AI infra, deployment frameworks. The code-card preview is bait: it signals 'this product is for people who read code,' which filters the leads correctly. Pairs with self-serve sign-up, generous free tiers, and engineer-led marketing on Twitter and Hacker News. Less useful for non-technical SaaS where Documentary B2B's credentialing converts better.",
}

export function getPortfolioCopy(slug: string): string {
  return (
    portfolioCopy[slug] ??
    "A production-grade design from the Apex Sites portfolio."
  )
}
