import type { Theme } from "./types"

export const heritagePainters: Theme = {
  slug: "heritage-painters",
  name: "Heritage Painters",
  industry: "Painting",
  city: "Charleston",
  tagline: "Premium house painting. 2-year warranty.",
  description:
    "Warm premium. Editorial Fraunces serif, ivory + terracotta + ink, gallery-led hero. For premium project work.",
  mode: "project",
  vibe: "warm-premium",
  hero: "gallery",
  heroEyebrow: "EST. 2008 — CHARLESTON",
  colors: {
    bg: "#FAF6EE",
    fg: "#1A1614",
    primary: "#1A1614",
    primaryFg: "#FAF6EE",
    accent: "#C8634A",
    accentFg: "#FAF6EE",
    muted: "#E8DFC8",
    mutedFg: "#6B6259",
    border: "#1A161414",
    surface: "#FFFFFF",
    surfaceFg: "#1A1614",
  },
  colorVariants: [
    {
      name: "Slate Brass",
      colors: {
        bg: "#F2EEE6",
        fg: "#15191C",
        primary: "#15191C",
        primaryFg: "#F2EEE6",
        accent: "#A07338",
        accentFg: "#F2EEE6",
        muted: "#DCD7CB",
        mutedFg: "#5C5F62",
        border: "#15191C14",
        surface: "#FAF8F4",
        surfaceFg: "#15191C",
      },
    },
    {
      name: "Garden Sage",
      colors: {
        bg: "#F4F1E8",
        fg: "#1A1F18",
        primary: "#1A1F18",
        primaryFg: "#F4F1E8",
        accent: "#5C7A4A",
        accentFg: "#F4F1E8",
        muted: "#DCE2D2",
        mutedFg: "#5F6358",
        border: "#1A1F1814",
        surface: "#FFFFFF",
        surfaceFg: "#1A1F18",
      },
    },
  ],
  fonts: { display: "fraunces", body: "inter", mono: "jetbrains-mono" },
  radius: { sm: "4px", md: "6px", lg: "8px", pill: "100px" },
  button: { shape: "sharp", shadow: "none", weight: "bold", uppercase: false },
  seoTitle: "Apex Sites — Warm Premium Editorial Style for Craft Brands",
  seoDescription:
    "The Heritage Painters demo. Editorial serif, ivory + terracotta + gold palette, gallery hero. For painters, restorers, and high-craft trades.",
  isThemeOption: true,
  sourceHtmlPath: "04-heritage-painters.html",
  round: 3,
}
