import type { Theme } from "./types"

export const brightsideCleaning: Theme = {
  slug: "brightside-cleaning",
  name: "Brightside Cleaning",
  industry: "Cleaning",
  city: "Seattle",
  tagline: "Book a home cleaning in 60 seconds. Flat-rate, no contracts.",
  description:
    "Friendly modern with sky + mint gradient. Plus Jakarta Sans + Caveat script. Booking-card hero.",
  mode: "recurring",
  vibe: "friendly-modern",
  hero: "booking-card",
  heroEyebrow: "BOOK ONLINE — INSTANT PRICE",
  colors: {
    bg: "#FAFCFE",
    fg: "#15293D",
    primary: "#4FA8E0",
    primaryFg: "#FFFFFF",
    accent: "#6FCFB6",
    accentFg: "#15293D",
    muted: "#C9E6F7",
    mutedFg: "#6B7B8C",
    border: "#15293D14",
    surface: "#FFFFFF",
    surfaceFg: "#15293D",
  },
  colorVariants: [
    {
      name: "Lavender Lemon",
      colors: {
        bg: "#FAFAFE",
        fg: "#1F1F3D",
        primary: "#7C5BD9",
        primaryFg: "#FFFFFF",
        accent: "#F7D26B",
        accentFg: "#1F1F3D",
        muted: "#E1D9F7",
        mutedFg: "#6B6B8C",
        border: "#1F1F3D14",
        surface: "#FFFFFF",
        surfaceFg: "#1F1F3D",
      },
    },
    {
      name: "Coral Cream",
      colors: {
        bg: "#FFFAF4",
        fg: "#2D1F1F",
        primary: "#FF6F61",
        primaryFg: "#FFFFFF",
        accent: "#FFB74D",
        accentFg: "#2D1F1F",
        muted: "#FFE2D9",
        mutedFg: "#7B5C5C",
        border: "#2D1F1F14",
        surface: "#FFFFFF",
        surfaceFg: "#2D1F1F",
      },
    },
  ],
  fonts: { display: "plus-jakarta-sans", body: "plus-jakarta-sans", mono: "jetbrains-mono" },
  radius: { sm: "10px", md: "14px", lg: "28px", pill: "100px" },
  button: { shape: "pill", shadow: "soft", weight: "bold", uppercase: false },
  seoTitle: "Apex Sites — Friendly Modern Booking-Card Style",
  seoDescription:
    "The Brightside Cleaning demo. Sky + mint gradient, soft pillowy cards, instant-book hero. For cleaners, dog walkers, and recurring home services.",
  isThemeOption: true,
  sourceHtmlPath: "05-brightside-cleaning.html",
  round: 3,
}
