import type { Theme } from "./types"

export const westwoodTree: Theme = {
  slug: "westwood-tree",
  name: "Westwood Tree Care",
  industry: "Tree Care",
  city: "Portland",
  tagline: "ISA Certified Arborists. Free estimate.",
  description:
    "Naturalist + safety-orange. Forest greens, editorial Fraunces serif. Gallery hero for project showcase.",
  mode: "project",
  vibe: "naturalist",
  hero: "gallery",
  heroEyebrow: "ISA CERTIFIED — FULLY INSURED",
  colors: {
    bg: "#F5F1E6",
    fg: "#1A1612",
    primary: "#FF6A1A",
    primaryFg: "#122019",
    accent: "#1F3528",
    accentFg: "#F5F1E6",
    muted: "#ECE5D2",
    mutedFg: "#6B6259",
    border: "#1F352826",
    surface: "#FAF6EC",
    surfaceFg: "#1A1612",
  },
  colorVariants: [
    {
      name: "Deep Forest",
      colors: {
        bg: "#F2EDE0",
        fg: "#15191A",
        primary: "#1B4332",
        primaryFg: "#F5F1E6",
        accent: "#A0522D",
        accentFg: "#F5F1E6",
        muted: "#E5DEC8",
        mutedFg: "#5C5F58",
        border: "#1B433226",
        surface: "#FAF6EC",
        surfaceFg: "#15191A",
      },
    },
    {
      name: "Burgundy Heritage",
      colors: {
        bg: "#F5F1E6",
        fg: "#1A1612",
        primary: "#7D3C2E",
        primaryFg: "#F5F1E6",
        accent: "#1F3528",
        accentFg: "#F5F1E6",
        muted: "#ECE5D2",
        mutedFg: "#6B6259",
        border: "#7D3C2E26",
        surface: "#FAF6EC",
        surfaceFg: "#1A1612",
      },
    },
  ],
  fonts: { display: "fraunces", body: "inter", mono: "jetbrains-mono" },
  radius: { sm: "0", md: "2px", lg: "4px", pill: "0" },
  button: { shape: "sharp", shadow: "hard-offset", weight: "heavy", uppercase: true },
  heroImage: {
    url: "/themes/westwood-tree/hero.jpg",
    alt: "Tall trees seen from below against a bright canopy of leaves",
    credit: "Photo by Sergei Akulich on Unsplash",
  },

  seoTitle: "Apex Sites — Naturalist Style with Safety-Orange Accents",
  seoDescription:
    "The Westwood Tree Care demo. Forest greens, safety orange, gallery hero. For arborists, landscapers, and rugged outdoor trades.",
  isThemeOption: true,
  sourceHtmlPath: "07-westwood-tree.html",
  round: 3,
}
