import type { Theme } from "./types"

export const voltcraftElectric: Theme = {
  slug: "voltcraft-electric",
  name: "Voltcraft Electric",
  industry: "Electrical",
  city: "Phoenix",
  tagline: "Master electricians. EV chargers, panels, 24/7 service.",
  description:
    "High-voltage industrial. Black + electric yellow, Inter heavy + JetBrains Mono. Phone-first hero.",
  mode: "emergency",
  vibe: "bold-industrial",
  hero: "phone-first",
  heroEyebrow: "LICENSED & BONDED — 24/7",
  colors: {
    bg: "#F4F4F5",
    fg: "#0A0A0A",
    primary: "#FFD500",
    primaryFg: "#0A0A0A",
    accent: "#0A0A0A",
    accentFg: "#FFD500",
    muted: "#D4D4D8",
    mutedFg: "#6E6E70",
    border: "#0A0A0A",
    surface: "#FFFFFF",
    surfaceFg: "#0A0A0A",
  },
  colorVariants: [
    {
      name: "Cobalt Voltage",
      colors: {
        bg: "#F4F4F5",
        fg: "#0A0A0A",
        primary: "#1D4ED8",
        primaryFg: "#FFFFFF",
        accent: "#0A0A0A",
        accentFg: "#1D4ED8",
        muted: "#D4D4D8",
        mutedFg: "#6E6E70",
        border: "#0A0A0A",
        surface: "#FFFFFF",
        surfaceFg: "#0A0A0A",
      },
    },
    {
      name: "Phosphor Green",
      colors: {
        bg: "#F4F4F5",
        fg: "#0A0A0A",
        primary: "#22C55E",
        primaryFg: "#0A0A0A",
        accent: "#0A0A0A",
        accentFg: "#22C55E",
        muted: "#D4D4D8",
        mutedFg: "#6E6E70",
        border: "#0A0A0A",
        surface: "#FFFFFF",
        surfaceFg: "#0A0A0A",
      },
    },
  ],
  fonts: { display: "inter", body: "inter", mono: "jetbrains-mono" },
  radius: { sm: "0", md: "0", lg: "0", pill: "0" },
  button: { shape: "sharp", shadow: "hard-offset", weight: "heavy", uppercase: false },
  seoTitle: "Apex Sites — Electric-Yellow Industrial Style for Trades",
  seoDescription:
    "The Voltcraft Electric demo. Black + voltage-yellow, mono accents, phone-first hero. For electricians, HVAC, and any 24/7 licensed trade.",
  isThemeOption: true,
  sourceHtmlPath: "08-voltcraft-electric.html",
  round: 3,
}
